host: 127.0.0.1
port: 23366
locale: zh-TW
timezone: Asia/Taipei
site_default: SHUANTT
login_timeout: 259200
db:
  type: pgsql
  table_prefix: atk_
  prepare_stmt: false
http:
  body_limit: 2
  proxy_header: ''
log:
  enabled: false
cache:
  enabled: false
ssl:
  enabled: false
moderator:
  pending_default: false
  api_fail_block: true
captcha:
  enabled: true
  always: true
  captcha_type: turnstile
  action_limit: 3
  action_reset: 60
img_upload:
  enabled: true
  max_size: 1
email:
  enabled: false
  send_type: smtp
  send_name: SHUANTT
  mail_subject: '[SHUANTT] 你的留言收到新回覆'
  mail_tpl: default
  smtp:
    host: smtp.gmail.com
    port: 587
admin_notify:
  notify_tpl: default
  notify_pending: true
  noise_mode: true
  email:
    enabled: true
    mail_subject: '[SHUANTT] 有新的文章留言'
auth:
  enabled: false
  anonymous: true
  email:
    enabled: false
frontend:
  uaBadge: false
  versionCheck: false
  gravatar:
    mirror: /static/images/comment-avatar.svg
    params: ''
